/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IMFrame.java
 *
 * Created on 3 Oct, 2010, 11:15:48 AM
 */
package jbapps.ui;

import java.awt.event.KeyEvent;
import jbapps.App;
import jbapps.model.User;

/**
 *
 * @author jb
 */
public class IMFrameUI extends javax.swing.JFrame {

    /** Creates new form IMFrame */
    public IMFrameUI(App _app) {
        initComponents();
        app = _app;
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chatUserLabel2 = new javax.swing.JLabel();
        chatUserLabel1 = new javax.swing.JLabel();
        chatScrollPane = new javax.swing.JScrollPane();
        chatTextPane = new javax.swing.JTextPane();
        inputScrollPane = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        chatUserLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chatUserLabel2.setText("User:");

        chatUserLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chatUserLabel1.setText("User:");

        chatTextPane.setEditable(false);
        chatTextPane.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chatTextPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        chatScrollPane.setViewportView(chatTextPane);

        inputTextArea.setColumns(20);
        inputTextArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        inputTextArea.setRows(5);
        inputTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTextAreaKeyReleased(evt);
            }
        });
        inputScrollPane.setViewportView(inputTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chatUserLabel1)
                        .addComponent(chatUserLabel2)
                        .addComponent(chatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addComponent(inputScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(chatUserLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(chatUserLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(chatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(inputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextAreaKeyReleased

        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String s = inputTextArea.getText();
            s = s.substring(0, s.lastIndexOf("\n"));
            app.sendIM(user, s);
            updateDialog("(( " + s);
            inputTextArea.setText("");
        }

    }//GEN-LAST:event_inputTextAreaKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.err.println("formWindowClosed: ");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        System.err.println("formWindowIconified: ");
    }//GEN-LAST:event_formWindowIconified

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.err.println("formWindowClosing: ");
        if (app != null)
            app.closeIMDialog(user);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane chatScrollPane;
    public javax.swing.JTextPane chatTextPane;
    public javax.swing.JLabel chatUserLabel1;
    public javax.swing.JLabel chatUserLabel2;
    public javax.swing.JScrollPane inputScrollPane;
    public javax.swing.JTextArea inputTextArea;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    //
    private String dialog = "";
    private User user;
    private App app;

    /**
     * @return the dialog
     */
    public String getDialog() {
        return dialog;
    }

    /**
     * @param dialog the dialog to set
     */
    public void updateDialog(String dialog) {
        this.dialog += (dialog + "\n");
        chatTextPane.setText(this.dialog);
    }

    /**
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user the user to set
     */
    public void setUser(User user) {
        this.user = user;
    }
}
